School.delete_all
School.create(id: 1, name: '上海健康医学院')
School.create(id: 2, name: '上海出版印刷高等专科学校')
School.create(id: 3, name: '上海公安高等专科学校')
School.create(id: 4, name: '上海工艺美术职业学院')
School.create(id: 5, name: '上海旅游高等专科学校')
School.create(id: 6, name: '上海电子信息职业技术学院')
School.create(id: 7, name: '上海农林职业技术学院')
School.create(id: 8, name: '上海行健职业学院')
School.create(id: 9, name: '上海海事职业技术学院')
School.create(id: 10, name: '上海交通职业技术学院')
School.create(id: 11, name: '上海城建职业学院')
School.create(id: 12, name: '上海科学技术职业学院')
School.create(id: 13, name: '上海体育职业学院')
School.create(id: 14, name: '上海工会管理职业学院')
School.create(id: 15, name: '上海工商外国语职业学院')
School.create(id: 16, name: '上海立达职业技术学院')
School.create(id: 17, name: '上海东海职业技术学院')
School.create(id: 18, name: '上海工商职业技术学院')
School.create(id: 19, name: '上海济光职业技术学院')
School.create(id: 20, name: '上海中侨职业技术学院')
School.create(id: 21, name: '上海思博职业技术学院')
School.create(id: 22, name: '上海震旦职业学院')
School.create(id: 23, name: '上海邦德职业技术学院')
School.create(id: 24, name: '上海电影艺术职业学院')
School.create(id: 25, name: '上海民远职业技术学院')
School.create(id: 26, name: '上海第二工业大学高等职业技术学院')
School.create(id: 27, name: '上海工程技术大学高职学院')
School.create(id: 28, name: '上海电机学院高职学院')
School.create(id: 29, name: '上海商学院高等技术学院')
School.create(id: 30, name: '上海应用技术大学高职学院')
School.create(id: 31, name: '上海立信会计学院高职学院')
School.create(id: 32, name: '上海民航职业技术学院')
School.create(id: 33, name: '上海杉达学院')
# 超级管理员，显示所有报名记录
School.create(id: 34, name: '信息化教学指导委员会')
School.create(id: 35, name: '上海海事大学高等技术学院')

SchoolUser.delete_all
SchoolUser.create(phone: '上海健康医学院', password: "265098", school_id: 1)
SchoolUser.create(phone: '上海出版印刷高等专科学校', password: "870596", school_id: 2)
SchoolUser.create(phone: '上海公安高等专科学校', password: "596174", school_id: 3)
SchoolUser.create(phone: '上海工艺美术职业学院', password: "150296", school_id: 4)
SchoolUser.create(phone: '上海旅游高等专科学校', password: "614357", school_id: 5)
SchoolUser.create(phone: '上海电子信息职业技术学院', password: "015936", school_id: 6)
SchoolUser.create(phone: '上海农林职业技术学院', password: "368729", school_id: 7)
SchoolUser.create(phone: '上海行健职业学院', password: "183954", school_id: 8)
SchoolUser.create(phone: '上海海事职业技术学院', password: "570692", school_id: 9)
SchoolUser.create(phone: '上海交通职业技术学院', password: "362140", school_id: 10)
SchoolUser.create(phone: '上海城建职业学院', password: "485327", school_id: 11)
SchoolUser.create(phone: '上海科学技术职业学院', password: "749860", school_id: 12)
SchoolUser.create(phone: '上海体育职业学院', password: "620395", school_id: 13)
SchoolUser.create(phone: '上海工会管理职业学院', password: "431206", school_id: 14)
SchoolUser.create(phone: '上海工商外国语职业学院', password: "406753", school_id: 15)
SchoolUser.create(phone: '上海立达职业技术学院', password: "189507", school_id: 16)
SchoolUser.create(phone: '上海东海职业技术学院', password: "560193", school_id: 17)
SchoolUser.create(phone: '上海工商职业技术学院', password: "162985", school_id: 18)
SchoolUser.create(phone: '上海济光职业技术学院', password: "981604", school_id: 19)
SchoolUser.create(phone: '上海中侨职业技术学院', password: "954670", school_id: 20)
SchoolUser.create(phone: '上海思博职业技术学院', password: "239710", school_id: 21)
SchoolUser.create(phone: '上海震旦职业学院', password: "237691", school_id: 22)
SchoolUser.create(phone: '上海邦德职业技术学院', password: "461205", school_id: 23)
SchoolUser.create(phone: '上海电影艺术职业学院', password: "502163", school_id: 24)
SchoolUser.create(phone: '上海民远职业技术学院', password: "364910", school_id: 25)
SchoolUser.create(phone: '上海第二工业大学高等职业技术学院', password: "479063", school_id: 26)
SchoolUser.create(phone: '上海工程技术大学高职学院', password: "849276", school_id: 27)
SchoolUser.create(phone: '上海电机学院高职学院', password: "491037", school_id: 28)
SchoolUser.create(phone: '上海商学院高等技术学院', password: "045382", school_id: 29)
SchoolUser.create(phone: '上海应用技术大学高职学院', password: "850142", school_id: 30)
SchoolUser.create(phone: '上海立信会计学院高职学院', password: "618327", school_id: 31)
SchoolUser.create(phone: '上海民航职业技术学院', password: "543179", school_id: 32)
SchoolUser.create(phone: '上海杉达学院', password: "504681", school_id: 33)
SchoolUser.create(phone: '信息化教学指导委员会', password: "000000", school_id: "34")
SchoolUser.create(phone: '上海海事大学高等技术学院', password: "000000", school_id: "35")

User.delete_all
User.create(id: 1, phone: '11111111', password: "111111", school_id: 1)
