# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e6ffd6c13698988336dfcfea17d5a8752a0e1e28d9f6ec1439aab4f551f9aa532a7c7079eae0a1d8e50609786c3ef1c23e9585855e576198f77a5d6891142bf

test:
  secret_key_base: 39ad5d8d8dc53b12c2ccb13ecc613eb07cbd24531d7a36e39f00487cc9bd57b5ccae2f3c0e39b647cbabe2c4edc8d32c7ecf1c9d80e2b4e28e4997fb562bff68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
